### ISSUE TITLE
I like it :>

### ISSUE THREAD

**Issue by Crazygamerxs** [praiseprince/NaiveBayesSMSClassifier#1]
Noice project u got there, pp. I tried it and it works surprisingly well, verified most of the spam messages as spam, i tried a lot, and the website is cute too, EXCEPT 
![image](https://github.com/user-attachments/assets/555ae771-37f4-485a-99e6-389378798111)

Now I have no clue as to how this works, but according to my 10 min research on Wikipedia, it classifies different attributes (one word in this case), and see how many times they appear in a dataset and then determine the likelihood of it being spam or ham or whatever u wanna do (why am i telling this to you).

I got a question, what if there is a word that appears in spam messages a lot, but you need the whole sentence for that word to see "yeah that sentence doesn't appear in a spam", cause this program checks for singular words

Otherwise it's pretty dope, I approve this Project!
![image](https://github.com/user-attachments/assets/68a9d717-8d95-4155-8b0b-31d3a2219377)

**Comment by praiseprince** [comment]
> I got a question, what if there is a word that appears in spam messages a lot, but you need the whole sentence for that word to see "yeah that sentence doesn't appear in a spam", cause this program checks for singular words

The Naive Bayes approach assumes that each word in a sentence is independent of the others, which is a significant limitation. This means it doesn't consider the context or the dependency between words. As a result, it can mistakenly classify messages based on the presence of certain words, without considering the full sentence. This is one reason why my Naive Bayes model has an accuracy of 88%.

It's a bit complicated to calculate the probability of an email directly, `P(Email)`. Instead, we assume that each word in the email is independent, which is a problematic assumption because, in a spam message, for example, the presence of words like "free" and "money" are often dependent on each other. Under this assumption, we approximate `P(Email)` as:

`P(Email) = P(word1) * P(word2) * ... * P(wordN)`

A better approach would be to use a model like logistic regression, which can understand the relationships between words by assigning weights to them. This helps the model make more accurate predictions by considering how words work together in context. I'm currently working on implementing this, so stay tuned!

> Otherwise it's pretty dope, I approve this Project!

![image](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWU4YzdsNTgybnprb3dydGEyNWU5bzJ6OW9od2VsZmlwdzZ5a2RpbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/x4dS8uOkeEFdxvV1nz/giphy.gif)

**Comment by Crazygamerxs** [comment]
ohhh makes sense, thanks for your insights sire, looking forward to see the logistic regression implementation. 

![image](https://github.com/user-attachments/assets/8acd8c13-86e7-4daf-9ddf-148078e318b3)
